# -----------------------------
# âš™ï¸ Project Configuration
# -----------------------------

project:
  name: "{{ cookiecutter.project_name }}"
  author: "{{ cookiecutter.author_name }}"
  version: "0.1.0"
  description: "{{ cookiecutter.description }}"

# -----------------------------
# ğŸ“¦ Project Paths
# -----------------------------
paths:
  root: "{{ cookiecutter.repo_name }}"
  config: "config/config.yaml"

# -----------------------------
# ğŸ“ Data Paths
# -----------------------------
path_data:
  raw: "data/raw"
  interim: "data/interim"
  processed: "data/processed"
  external: "data/external"

